Bump to 0.25.2
Quentinchampenois/decidim-module_phone_authorization_handler pull request #9
Opened 2022-03-03 18:39 UTC by Quentinchampenois

#### Description

Bump module to 0.25.2

#### Tasks

- [x] Add webpacker
- [x] Sanitize and refactor code
- [x] Update tests
- [x] Change overrides for extends when possible
- [x]  Ensure privacy on exports
- [ ] Allow deactivate private exports

2022-03-04 09:57 UTC, eliegaboriau approved these changes

2022-03-07 14:19 UTC, armandfardeau requested changes
Can you remove circleci folder please?

2022-03-14 16:18 UTC, armandfardeau approved these changes

2022-03-29 14:09 UTC, armandfardeau approved these changes

2022-03-29 14:12 UTC, paulinebessoles approved these changes

2023-12-08 15:59 UTC, merged